## *********************************************************
## 
## File autogenerated for the ecjtu_rgbd_slam package 
## by the dynamic_reconfigure package.
## Please do not edit.
## 
## ********************************************************/

##**********************************************************
## Software License Agreement (BSD License)
##
##  Copyright (c) 2008, Willow Garage, Inc.
##  All rights reserved.
##
##  Redistribution and use in source and binary forms, with or without
##  modification, are permitted provided that the following conditions
##  are met:
##
##   * Redistributions of source code must retain the above copyright
##     notice, this list of conditions and the following disclaimer.
##   * Redistributions in binary form must reproduce the above
##     copyright notice, this list of conditions and the following
##     disclaimer in the documentation and/or other materials provided
##     with the distribution.
##   * Neither the name of the Willow Garage nor the names of its
##     contributors may be used to endorse or promote products derived
##     from this software without specific prior written permission.
##
##  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
##  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
##  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
##  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
##  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
##  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
##  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
##  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
##  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
##  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
##  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
##  POSSIBILITY OF SUCH DAMAGE.
##**********************************************************/

from dynamic_reconfigure.encoding import extract_params

inf = float('inf')

config_description = {'upper': 'DEFAULT', 'lower': 'groups', 'srcline': 233, 'name': 'Default', 'parent': 0, 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'cstate': 'true', 'parentname': 'Default', 'class': 'DEFAULT', 'field': 'default', 'state': True, 'parentclass': '', 'groups': [], 'parameters': [{'srcline': 259, 'description': '', 'max': True, 'cconsttype': 'const bool', 'ctype': 'bool', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'name': 'run_dense_tracking', 'edit_method': '', 'default': False, 'level': 1, 'min': False, 'type': 'bool'}, {'srcline': 259, 'description': '', 'max': True, 'cconsttype': 'const bool', 'ctype': 'bool', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'name': 'use_dense_tracking_estimate', 'edit_method': '', 'default': False, 'level': 2, 'min': False, 'type': 'bool'}, {'srcline': 259, 'description': '', 'max': 5, '
cconsttype': 'const int', 'ctype': 'int', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'name': 'coarsest_level', 'edit_method': '', 'default': 3, 'level': 4, 'min': 0, 'type': 'int'}, {'srcline': 259, 'description': '', 'max': 5, 'cconsttype': 'const int', 'ctype': 'int', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'name': 'finest_level', 'edit_method': '', 'default': 1, 'level': 4, 'min': 0, 'type': 'int'}, {'srcline': 259, 'description': '', 'max': 500, 'cconsttype': 'const int', 'ctype': 'int', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'name': 'max_iterations', 'edit_method': '', 'default': 50, 'level': 4, 'min': 1, 'type': 'int'}, {'srcline': 259, 'description': '', 'max': 1.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'name': '
precision', 'edit_method': '', 'default': 0.0001, 'level': 4, 'min': 0.0, 'type': 'double'}, {'srcline': 259, 'description': '', 'max': True, 'cconsttype': 'const bool', 'ctype': 'bool', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'name': 'use_initial_estimate', 'edit_method': '', 'default': True, 'level': 4, 'min': False, 'type': 'bool'}, {'srcline': 259, 'description': '', 'max': True, 'cconsttype': 'const bool', 'ctype': 'bool', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'name': 'use_weighting', 'edit_method': '', 'default': False, 'level': 4, 'min': False, 'type': 'bool'}, {'srcline': 259, 'description': '', 'max': 20, 'cconsttype': 'const int', 'ctype': 'int', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'name': 'scale_estimator', 'edit_method': "{'enum_description': 'scale estimator', 'enum': [{'srcline': 27, 'description': '', 'srcfile':
 '../cfg/dvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'NormalDistributionScaleEstimator'}, {'srcline': 28, 'description': '', 'srcfile': '../cfg/dvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'TDistributionScaleEstimator'}, {'srcline': 29, 'description': '', 'srcfile': '../cfg/dvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'MADScaleEstimator'}]}", 'default': 2, 'level': 4, 'min': 0, 'type': 'int'}, {'srcline': 259, 'description': '', 'max': 100.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'name': 'scale_estimator_param', 'edit_method': '', 'default': 5.0, 'level': 4, 'min': 0.0, 'type': 'double'}, {'srcline': 259, 'description': '', 'max': 20, 'cconsttype': 'const int', 'ctype': 'int', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.
py', 'name': 'influence_function', 'edit_method': "{'enum_description': 'influence function', 'enum': [{'srcline': 34, 'description': '', 'srcfile': '../cfg/dvo.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'TukeyInfluenceFunction'}, {'srcline': 35, 'description': '', 'srcfile': '../cfg/dvo.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'TDistributionInfluenceFunction'}, {'srcline': 36, 'description': '', 'srcfile': '../cfg/dvo.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'HuberInfluenceFunction'}]}", 'default': 2, 'level': 4, 'min': 0, 'type': 'int'}, {'srcline': 259, 'description': '', 'max': 100.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'name': 'influence_function_param', 'edit_method': '', 'default': 5.0, 'level': 4, 'min': 0.0, 'type': 'double'}, {'srcline': 259, 'description': '', '
max': 255.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'name': 'min_intensity_deriv', 'edit_method': '', 'default': 0.0, 'level': 4, 'min': 0.0, 'type': 'double'}, {'srcline': 259, 'description': '', 'max': 10.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'name': 'min_depth_deriv', 'edit_method': '', 'default': 0.0, 'level': 4, 'min': 0.0, 'type': 'double'}, {'srcline': 259, 'description': '', 'max': 10.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'name': 'lambda', 'edit_method': '', 'default': 0.0, 'level': 4, 'min': 0.0, 'type': 'double'}, {'srcline': 259, 'description': '', 'max': 10.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/
dynamic_reconfigure/parameter_generator.py', 'name': 'mu', 'edit_method': '', 'default': 0.0, 'level': 4, 'min': 0.0, 'type': 'double'}, {'srcline': 259, 'description': '', 'max': True, 'cconsttype': 'const bool', 'ctype': 'bool', 'srcfile': '/opt/ros/hydro/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py', 'name': 'reconstruction', 'edit_method': '', 'default': True, 'level': 8, 'min': False, 'type': 'bool'}], 'type': '', 'id': 0}

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

#def extract_params(config):
#    params = []
#    params.extend(config['parameters'])    
#    for group in config['groups']:
#        params.extend(extract_params(group))
#    return params

for param in extract_params(config_description):
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

EcjtuRgbdSLAM_RunDenseTracking = 1
EcjtuRgbdSLAM_UseDenseTrackingEstimate = 2
EcjtuRgbdSLAM_ConfigParam = 4
EcjtuRgbdSLAM_MiscParam = 8
EcjtuRgbdSLAM_NormalDistributionScaleEstimator = 1
EcjtuRgbdSLAM_TDistributionScaleEstimator = 2
EcjtuRgbdSLAM_MADScaleEstimator = 3
EcjtuRgbdSLAM_TukeyInfluenceFunction = 1
EcjtuRgbdSLAM_TDistributionInfluenceFunction = 2
EcjtuRgbdSLAM_HuberInfluenceFunction = 3
